from typing import Iterator, List, Optional, Tuple, Union
from .tensor import Tensor

class Module:
    def __init__(self) -> None: ...
    def forward(self, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
    def __call__(self, *args: Tensor, **kwargs: Tensor) -> Tensor: ...
    def parameters(self) -> List[Tensor]: ...
    def zero_grad(self) -> None: ...
    def to(self, device: str) -> Module: ...

class Linear(Module):
    in_features: int
    out_features: int
    use_bias: bool
    weight: Tensor
    bias: Optional[Tensor]

    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class ReLU(Module):
    def __init__(self) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class MSELoss(Module):
    def __init__(self) -> None: ...
    def forward(self, y_pred: Tensor, y_true: Tensor) -> Tensor: ...

class Sequential(Module):
    def __init__(self, *modules: Module) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Module: ...
    def forward(self, x: Tensor) -> Tensor: ...
