from typing import Iterable, List
from .tensor import Tensor

class Optimizer:
    params: List[Tensor]
    def __init__(self, params: Iterable[Tensor]) -> None: ...
    def zero_grad(self) -> None: ...
    def step(self) -> None: ...
    async def step_async(self) -> None: ...

class SGD(Optimizer):
    lr: float
    def __init__(self, params: Iterable[Tensor], lr: float = 0.01) -> None: ...
    def step(self) -> None: ...
    async def step_async(self) -> None: ...
