from typing import Any, Sequence, Union, Optional, Tuple
import numpy as np

ArrayLike = Union[Sequence[Any], np.ndarray, float, int]

class Tensor:
    _handle: Optional[str]
    _shape: Tuple[int, ...]
    _dtype: str
    _device: str
    _requires_grad: bool
    _grad: Optional[Tensor]
    _data: Optional[np.ndarray]
    _version: int

    def __init__(
        self,
        data: Optional[ArrayLike] = None,
        shape: Optional[Sequence[int]] = None,
        dtype: str = "float32",
        device: str = "cpu",
        requires_grad: bool = False,
        handle: Optional[str] = None,
    ) -> None: ...

    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def requires_grad(self) -> bool: ...
    @requires_grad.setter
    def requires_grad(self, value: bool) -> None: ...
    @property
    def grad(self) -> Optional[Tensor]: ...
    @grad.setter
    def grad(self, value: Optional[Tensor]) -> None: ...

    def to(self, device: str) -> Tensor: ...
    def backward(self, grad: Optional[Tensor] = None, retain_graph: bool = False) -> None: ...
    def realize(self) -> Tensor: ...
    def dispose(self) -> None: ...
    async def numpy_async(self) -> np.ndarray: ...
    def numpy(self) -> np.ndarray: ...

    def __add__(self, other: Union[Tensor, float, int]) -> Tensor: ...
    def __sub__(self, other: Union[Tensor, float, int]) -> Tensor: ...
    def __mul__(self, other: Union[Tensor, float, int]) -> Tensor: ...
    def __truediv__(self, other: Union[Tensor, float, int]) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def reshape(self, *shape: int) -> Tensor: ...
    def transpose(self, dim0: int = 0, dim1: int = 1) -> Tensor: ...

def tensor(
    data: Optional[ArrayLike] = None,
    shape: Optional[Sequence[int]] = None,
    dtype: str = "float32",
    device: str = "cpu",
    requires_grad: bool = False,
) -> Tensor: ...
