#!/usr/bin/env python3
"""
Builds docs/dist/forge-py-bundle.js from packages/forge-py/src/forge directory.
"""

import os
import json
from pathlib import Path

SRC_DIR = Path("packages/forge-py/src/forge")
OUTPUT_FILE = Path("docs/dist/forge-py-bundle.js")

def build_bundle():
    print(f"[*] Scanning {SRC_DIR} for Python source files...")
    bundle_files = {}

    for root, dirs, files in os.walk(SRC_DIR):
        for file in files:
            if file.endswith(".py"):
                full_path = Path(root) / file
                rel_path = full_path.relative_to(SRC_DIR).as_posix()
                with open(full_path, "r", encoding="utf-8") as f:
                    content = f.read()
                bundle_files[rel_path] = content
                print(f"  [+] Bundled: {rel_path} ({len(content)} chars)")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Autogenerated WebGPU Pyodide Bundle for AMEVA-Forge\n")
        f.write("window.__FORGE_PY_FILES__ = ")
        f.write(json.dumps(bundle_files, indent=2, ensure_ascii=False))
        f.write(";\n")

    print(f"[SUCCESS] Successfully generated {OUTPUT_FILE} ({len(bundle_files)} files bundled).")

if __name__ == "__main__":
    build_bundle()
